version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    # machine:
    #   image: ubuntu-1604:201903-01
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    working_directory: ~/pluto-core
    steps:
      - checkout
      - run:
          name: Build production
          command: |
            npm run build:production
