version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    # machine:
    #   image: ubuntu-1604:201903-01
    docker:
      # specify the version you desire here
      - image: circleci/node:8
    working_directory: ~/pluto-core
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Build production
          command: |
            npm run build:production

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
